### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by jose46moreno** [alexaubry/BulletinBoard#90] opened 2018-06-25 10:09 UTC
I installed the pod on iOS 11.3.

Then from the.swift file I made the BulletinBoard import but it doesn't give me any information about the library. He also doesn't recognize any of his classes and won't let me use them.

This is the error when I try to show the framework:

<img width="1440" alt="captura de pantalla 2018-06-25 a las 12 10 43" src="https://user-images.githubusercontent.com/8105593/41844567-de70353a-7870-11e8-8754-5d6a62e4f284.png">

**Comment by alexaubry** [comment] 2018-07-16 07:30
This is most likely an issue with your CocoaPods set up, as I could not reproduce this issue, even on computers where the library was never cloned before. 

Also, the name of the module is now `BLTNBoard`, I see you are trying to get the Swift header for `BulletinBoard`. Have you tried cleaning / deleting derived data?

**Comment by alexaubry** [comment] 2018-10-17 09:14
@jose46moreno I will close this issue for now. If you have another build issue, feel free to reopen another issue 😃

**Closed by alexaubry** 2018-10-17 09:14 UTC
Labels: question
