### ISSUE TITLE
Layout broken on iPad, app running in Split view

### ISSUE THREAD

**Issue by Piidro** [alexaubry/BulletinBoard#172] opened 2019-10-28 09:34 UTC
**Problem Description:**
Hello, seems that this library doesn't work when bulletin is opened when app is not taking 100% of the screen. When running in any split view combinations (1/4, 2/4, 3/4 or 1/3, 2/3 of the screen widths) the bulletin view is displayed as it would take the whole screen estate, therefore part of it is hidden. I have tried both `showBulletin(above:animated:completion:)` or `showBulletin(in:animated:completion)` they seem to give same result. I attach an image of the problem to further clarify the issue.

<img width="725" alt="Screenshot 2019-10-28 at 11 21 34" src="https://user-images.githubusercontent.com/1936449/67667579-cbabc580-f976-11e9-8de0-52254af4a5bf.png">

Is there any workaround?

**Steps to reproduce:**
Run the app, present bulletin board when app size has been reduced with split view. Present bulletin board with either `showBulletin(above:animated:completion:)` or `showBulletin(in:animated:completion)`

**Environment:**
 - Device: iPad 11" Pro, iPad 12.9" Pro
 - OS: iOS 13.0, 13.1, 13.2
 - Version of BulletinBoard: 4.1.0

**Comment by arguiot** [comment] 2019-11-05 00:46
I also have this problem @alexaubry could you have a look, please?

**Comment by Piidro** [comment] 2020-02-07 07:52
I think I managed to fix this issue. I opened up a PR #173 with the fix. I don't know if it is the correct way to go though but you who are interested on the subject can take a look!

**Comment by arguiot** [comment] 2020-02-07 12:29
Great, I’ll take a look and try to install it in my app to see if the issue is fixed.

**Comment by alexaubry** [comment] 2020-05-14 22:46
The fix was released in 4.1.1, thanks for your patience.

**Closed by alexaubry** 2020-05-14 22:46 UTC
