### ISSUE TITLE
Swipe action doesn't work on ios10.2

### ISSUE THREAD

**Issue by mitolog** [alexaubry/BulletinBoard#51] opened 2018-01-06 08:46 UTC
### New Issue Checklist

- [x] I updated BulletinBoard to the latest version.
- [x] I read the [Contribution Guidelines](https://github.com/alexaubry/BulletinBoard/blob/master/CONTRIBUTING.md).
- [x] I read the [documentation](https://alexaubry.github.io/BulletinBoard).
- [x] I searched for [existing GitHub issues](https://github.com/alexaubry/BulletinBoard/issues).

#### how to reproduce
1. launch sample app(BB-Swift Scheme)
2. press "Show Intro" button on the right navigation barbutton item
3. try to swipe up/down
4. then bulletinBoard and dimmed view doesn't respond anymore, only way to dismiss is just kill the app by pressing home button and open an app again.

#### quick workaround 
just comment out of *BulletinSwipeInteractionController.swif* line 45 `prepareGestureRecognizer()`, though pan action cannot be usable.

### Environment

- **iOS Version**: [ios10.2]
- **Device(s)**: [iphone6s, not simulator]

**Comment by mitolog** [comment] 2018-01-06 10:13
As a quick(nasty...) workaround, you should set `page.isDismissable = false` additionally, otherwise it may crash on 2-3 times swiping action on the card.

**Comment by alexaubry** [comment] 2018-05-27 13:58
This issue seems to be fixed with version `2.0.0-beta.3`, as changes have been made to the swipe gesture recognizer (users have to lift their finger to complete the dismissal). Please feel free to reopen this issue if you manage to reproduce it on this version or a later one.

**Closed by alexaubry** 2018-05-27 13:58 UTC
Labels: bug
