### ISSUE TITLE
Alternate button squashed

### ISSUE THREAD

**Issue by rossrossp** [alexaubry/BulletinBoard#24] opened 2017-11-17 12:21 UTC
Alternate button is squashed upon first load when keyboard moves up Bulletin:
![screen shot 2017-11-17 at 10 31 35](https://user-images.githubusercontent.com/6325131/32946990-b4a71f16-cb91-11e7-8ec0-de367032c170.png)

This also makes the button un-tappable.

This only happens on small screen devices (iPhone 5S/SE) on first load. If you go to the next page and then come back again, they are spaced correctly.

**Comment by alexaubry** [comment] 2017-11-17 16:29
Thank you for reporting 👍 

The problem is the `topAnchor` of the card is constrained to the top layout guide, to prevent it to show behind the status bar.

If you are using a custom bulletin item to create this interface, I think you could try to reduce the spacing between the _"Sign Up"_ label and the text field, as an immediate workaround.

I'll be working on a way to improve the handling of this situation.

**Comment by alexaubry** [comment] 2017-11-18 15:30
This should be fixed by 6df0ae9. Could you try to build the library from the master branch and tell me if your issue is fixed?

**Comment by alexaubry** [comment] 2017-12-05 14:50
It seems to be working fine for me, so I will close this issue for now. Feel free to reopen it if you still have this bug.

**Closed by alexaubry** 2017-12-05 14:50 UTC
Labels: bug, pending-feedback
